routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/////////////// Admin Routes ////////////////
Route::name('admin.')->namespace('Auth')->middleware('guest:admin')->group(function()
{
    Route::get('/', function() {
        return redirect(route('admin.login'));
    }); 

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('login.submit');

});

Route::name('admin.')->middleware(['auth:admin'])
->group(function() {

    Route::post('logout', 'Auth\LoginController@logout')->name('logout');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/newsletter', 'HomeController@newsletter')->name('newsletter');
    Route::post('/newsletter/store', 'HomeController@newsletterstore')->name('newsletter.store');

    Route::group(['prefix' => 'setting'], function() {

        Route::get('/', 'SettingController@index')->name('setting');
        Route::post('/appname', 'SettingController@updateappname')->name('setting.appname');
        Route::post('/logo', 'SettingController@updatelogo')->name('setting.logo');
        Route::post('/copyright', 'SettingController@updatecopyright')->name('setting.copyright');
        Route::post('/email', 'SettingController@updateadminemail')->name('setting.email');
        Route::post('/password', 'SettingController@updateadminpassword')->name('setting.password');

        Route::post('/app_address', 'SettingController@updatecompanyaddress')->name('setting.app_address');
        Route::post('/app_email', 'SettingController@updatecompanyemail')->name('setting.app_email');
        Route::post('/app_mobile', 'SettingController@updatecompanymobile')->name('setting.app_mobile');
   
    });

    Route::resource('socials', SocialController::class);
    Route::resource('products', ProductController::class);
    Route::resource('procategory', ProductCategoryController::class);
    Route::resource('services', ServiceController::class);
    
    Route::get('/product/image/{id}', 'ProductController@produtimagedelete')->name('product.image.delete');
    Route::post('/products/status/{id}', 'ProductController@updatestatus')->name('product.status');
    Route::post('/services/status/{id}', 'ServiceController@updatestatus')->name('services.status');

    Route::get('/feedback', 'FeedBackController@index')->name('feedback.index');
    Route::delete('/feedback/delete/{id}', 'FeedBackController@destroy')->name('feedback.delete');
    Route::get('/feedback/{id}/show', 'FeedBackController@feedbackshow')->name('feedback.show');
    Route::post('/feedback/reply', 'FeedBackController@feedbackreply')->name('feedback.reply');


    Route::get('/content', 'ContentController@index')->name('content.index');
    Route::get('/content/{id}', 'ContentController@edit')->name('content.edit');
    Route::put('/content/{id}', 'ContentController@update')->name('content.update');
    Route::get('/content/image/{id}', 'ContentController@deleteImage')->name('content.image.delete');
    Route::get('/content/video/{id}', 'ContentController@deletevideo')->name('content.video.delete');


    Route::group(['prefix' => 'web-user'], function() {

        Route::get('/', 'WebUserController@index')->name('webuser.index');
        Route::get('/get', 'WebUserController@get')->name('webuser.get');

        Route::get('/add', 'WebUserController@addUser')->name('webuser.add');
        Route::post('/store', 'WebUserController@storeUser')->name('webuser.store');
        Route::get('/edit/{id?}', 'WebUserController@editUser')->name('webuser.edit');
        Route::get('/show/{id?}', 'WebUserController@showUser')->name('webuser.show');
        Route::post('/update', 'WebUserController@updateUser')->name('webuser.update');
        Route::get('/delete/{id?}', 'WebUserController@userdelete')->name('webuser.delete');

        Route::post('/bulk-action', 'WebUserController@bulkAction')->name('webuser.bulkAction');
        Route::post('export-excel', 'WebUserController@excel_export')->name('webuser.export.excel');
        Route::post('/status/{id}', 'WebUserController@updatestatus')->name('webuser.status');
    });

});

routes/web.php
<?php

use App\Mail\TestMail;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/fcm/{message}/{token}', function ($message, $token)
// {
//    dd(fcm($token,'user', 'Play Pause Continue', $message, []));
// });

Route::get('/welcome', function () {
    return view('welcome');
}); 
Route::get('/', [App\Http\Controllers\IndexController::class, 'index'])->name('/');
// Route::get('/', [App\Http\Controllers\IndexController::class, 'index'])->name('index');
Route::get('/contact-us', [App\Http\Controllers\IndexController::class, 'contactUs'])->name('contactus');
Route::get('/career', [App\Http\Controllers\IndexController::class, 'career'])->name('career');
Route::get('/about-us', [App\Http\Controllers\IndexController::class, 'aboutUs'])->name('aboutus');
Route::get('/privacy-policy', [App\Http\Controllers\IndexController::class, 'privacypolicy'])->name('privacypolicy');
Route::get('/term-condition', [App\Http\Controllers\IndexController::class, 'termcondition'])->name('termcondition');
Route::get('/services', [App\Http\Controllers\IndexController::class, 'services'])->name('services');
Route::get('/services/{id}', [App\Http\Controllers\IndexController::class, 'serviceById'])->name('service_by_id');
Route::get('/who-we-are', [App\Http\Controllers\IndexController::class, 'who_we_are'])->name('who_we_are');
Route::get('/our-values', [App\Http\Controllers\IndexController::class, 'our_values'])->name('our_values');
Route::get('/our-history', [App\Http\Controllers\IndexController::class, 'our_history'])->name('our_history');
Route::get('/board-of-director', [App\Http\Controllers\IndexController::class, 'board_of_director'])->name('board_of_director');
Route::get('/management-team', [App\Http\Controllers\IndexController::class, 'management_team'])->name('management_team');
Route::get('/products', [App\Http\Controllers\IndexController::class, 'products'])->name('products');
Route::get('/products/{cat_id}', [App\Http\Controllers\IndexController::class, 'productByCategory'])->name('product_by_id');
Route::get('/products/detail/{product_id}', [App\Http\Controllers\IndexController::class, 'productDetail'])->name('productDetail');

Auth::routes();

Route::post('/feedback/store', [App\Http\Controllers\IndexController::class, 'feedback'])->name('feedback.store');
Route::post('/newsletter/store', [App\Http\Controllers\IndexController::class, 'newsletter'])->name('newsletter.store');
Route::post('/validatemobile', [App\Http\Controllers\IndexController::class, 'validatemobile'])->name('validatemobile');
Route::post('/validateemail', [App\Http\Controllers\IndexController::class, 'validateemail'])->name('validateemail');
Route::post('/validateuser', [App\Http\Controllers\IndexController::class, 'validateuser'])->name('validateuser');
Route::post('/sendotptomobile', [App\Http\Controllers\IndexController::class, 'sendotptomobile'])->name('sendotptomobile');

Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/mobile', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.mobile');

Route::post('/verifyotp', [App\Http\Controllers\IndexController::class, 'verifyotp'])->name('verifyotp');
Route::get('/resend-otp/{mobile}', [App\Http\Controllers\IndexController::class, 'resendotp'])->name('resendotp');

Route::middleware(['auth:customer'])->group(function()
{
    Route::get('/test', [App\Http\Controllers\IndexController::class, 'test']);
    Route::get('/home', [App\Http\Controllers\IndexController::class, 'index'])->name('home');
    Route::post('/save-token', [App\Http\Controllers\IndexController::class, 'saveToken'])->name('save-token');


    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
   
});

app/Models/FeedBack.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class FeedBack extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use Laravel\Passport\HasApiTokens;
use Illuminate\Support\Facades\Storage;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'my_refer_code',
        'user_type',
        'dob',
        'mobile',
        'address',
        'GST_number',
        'refferal_code',
        'send_password',
        'block',
        'latitude',
        'longitude',
        'fcm_token',
        'wallet_pin',
        'user_level',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'send_password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'user_level' => 'int',
        'block' => 'int',
    ];

    public function findForPassport($username)
    {
        return $this->where('email', $username)
        ->orWhere('mobile', $username)
        ->first();
    }

    public function getProfileImageAttribute($value)
    {
        return $value ? url(Storage::url('userprofile/'.$value)) : null;
    }

    public function getCreatedAtAttribute($value)
    {
        return $value ? \Carbon\Carbon::parse($value)->format('Y-m-d'): null;
    }

}

app/Http/Controllers/Admin/FeedBackController.php
<?php

namespace App\Http\Controllers\Admin;

use Exception;
use App\Models\FeedBack;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Validator;

class FeedBackController extends Controller
{
    public function index()
    {
        $data['feedback']=FeedBack::orderBy('id','desc')->get();
        return view('admin.feedback.index',$data);
    }
    public function destroy($id)
    {
        $feedback = FeedBack::where('id',$id)->first();

        if($feedback->delete())
        {
            return response()->json(['status' => '1','massage'=>'FeedBack Status Deleted!']);
        }
        else
        {
            return response()->json(['status' => '0','massage'=>'FeedBack Status Not Deleted!']);
        }

        // return redirect()->route('admin.feedback.index')->with('success','Feedback Deleted!');
    }

    public function feedbackshow($id)
    {
        $data['feedback']=FeedBack::find($id);
        return view('admin.feedback.show',$data);
    }

    public function feedbackreply(Request $request)
    {
        $validator=Validator::make($request->all(),[
            'reply'   => 'required',
        ]);
        if($validator->fails())
        {
            return redirect()->back()->withErrors($validator->errors())->withInput();
        }
        $addevent = FeedBack::where('id',$request->id)->first();
        $addevent->reply  = $request->reply;
        $addevent->save();
        if($addevent->email!=null)
        {
            try
            {
                $data = [
                    'subject' =>'',
                    'message' =>$request->reply,
                ];
                Mail::to($addevent->email)->send(new \App\Mail\Feedback($data));
            }
            catch(Exception $e)
            {

            }
        }
        return redirect()->route('admin.feedback.index')->with('success','Feedback Sent!');
    }

}

resources/views/admin/feedback/index.blade.php
@extends('admin.layouts.admin')

@push('style')
    <link href="{{ asset('css/plugins/dataTables/datatables.min.css') }}" rel="stylesheet">
@endpush

@section('content')

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-9">
            <h2>Contact Us List</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.home') }}">Home</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Contact Us</strong>
                </li>
            </ol>

        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5>Contact Us</h5>
                        <div class="ibox-tools">
                        </div>
                    </div>

                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover dataTables-example">
                                <thead>
                                    <tr>
                                        <th>S.No.</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Mobile</th>
                                        <th>Message</th>
                                        <th>Date</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($feedback as $item)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $item->name }}</td>
                                            <td>{{ $item->email?$item->email:'N/A' }}</td>
                                            <td>{{ $item->mobile?$item->mobile:'N/A' }}</td>
                                            <td>{{ \Illuminate\Support\Str::limit($item->message, 50, $end='...') }}</td>
                                            <td>{{ Carbon\Carbon::parse($item->created_at)->format('d M Y') }}</td>
                                            <td>
                                                {{-- <a class="btn btn-xs text-light btn-dark"
                                                    href="{{ route('admin.feedback.delete', $item->id) }}"><i
                                                        class="fa fa-trash"></i></a> --}}
                                                <a class="btn btn-xs text-light btn-warning"
                                                        href="{{ route('admin.feedback.show', $item->id) }}"><i
                                                            class="fa fa-eye"></i></a>
                                                <button style="margin:0 3px;"  class="btn btn-xs btn-dark demotest" title="View"  data-id="{{$item->id}}"><i class="fa fa-trash"></i></button> 
                               
                                            </td>
                                        </tr>
                                    @empty

                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@push('script')
    <script src="{{ asset('js/plugins/dataTables/datatables.min.js') }}"></script>
    <script src="{{ asset('js/plugins/dataTables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('js/plugins/sweetalert/sweetalert.min.js') }}"></script>

    <script>

        $(document).ready(function(){
            $('.dataTables-example').dataTable( {
                dom: "<'row'<'col-sm-3'l><'col-sm-5 text-center'B><'col-sm-3'f>>" +
                    "<'row'<'col-sm-12'tr>>" +
                    "<'row'<'col-sm-5'i><'col-sm-7'p>>",
                buttons:[
                            {
                                    extend: 'excel',
                                    footer: false,
                                    className: 'btn btn-primary',
                                    init: function(api, node, config) {
                                        $(node).removeClass('btn-default')
                                    },
                            },        
                        ]
            });
        });
        
        function mydeleteproduct(id) 
        {
            var id= id;
            var url="{{ url('admin/feedback/delete/')}}"+'/'+id;
            $.ajax({
                type: 'POST',
                dataType: 'json',
                data: {
                    id: id,
                    _token: "{{ csrf_token() }}",
                    _method: 'DELETE'
                },
                url: url,
                success: function (data) {
                    if(data.status=='1')
                    {
                        location.reload();
                    }
                    if(data.status=='0')
                    {
                        location.reload();
                    }
                },
                error: (err) => {
                    console.log(err);
                    swal("Error!", "", "error");
                },
            });
        
        }

        $(document).on('click', '.demotest', function() 
        {
            event.preventDefault();
            let id = $(this).attr('data-id');
            // alert(id);
            swal({
                title: "Are you sure?",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#233dc7",
                confirmButtonText: "Delete",
                cancelButtonText: "Cancel",
                closeOnConfirm: false,
                closeOnCancel: false },
                function (isConfirm) {
                    if (isConfirm) {
                        mydeleteproduct(id);
                    } else {
                        location.reload();
                    }
            });
        });

    </script>
@endpush

resources/views/admin/feedback/show.blade.php
@extends('admin.layouts.admin')

@push('style')
    <link href="{{ asset('css/plugins/dataTables/datatables.min.css') }}" rel="stylesheet">
@endpush

@section('content') 
<div class="mprofile-full-box">
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-9">
            <h2>Feedback Details</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.home') }}">Home</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Feedback Details</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-content">
                            <div class="flot-chart">
                                <div class="flot-chart-content" id="flot-bar-chart">

                                    <div class="row">
                                        <div class="col-md-2"><b>Name </b></div>
                                        <div class="col-md-10"> {{ $feedback->name}}</div>
                                    
                                    </div>
                                    <div class="row">
                                        <div class="col-md-2"><b>Email  </b></div>
                                        <div class="col-md-10"> {{ $feedback->email?$feedback->email:'N/A'}}</div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-2"><b>Mobile  </b></div>
                                        <div class="col-md-10"> {{ $feedback->mobile?$feedback->mobile:'N/A'}}</div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-2"><b>Message </b></div>
                                        <div class="col-md-10"> {{ $feedback->message}}</div>
                                    </div>  
                                    <div class="row">
                                        <div class="col-md-2"><b>Date </b></div>
                                        <div class="col-md-10"> {{ Carbon\Carbon::parse($feedback->created_at)->format('d M Y')}}</div>
                                    </div>                              
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
        @if($feedback->email!=null)
            {{-- <div class="row">
                <div class="col-lg-12">
                        <div class="ibox">
                            <div class="ibox-title">
                                <h5></h5>
                            </div>
                            <div class="ibox-content">
                                <form action="{{route('admin.feedback.reply')}}" method="POST">
                                    @csrf
                                    <div class="form-group row">
                                        <div class="col-sm-2 col-sm-offset-2">
                                            <b><span>Reply </span></b>
                                        </div>
                                        <div class="col-sm-8 mb-2">
                                            <input type="hidden" class="form-control" name="id" value="{{ $feedback->id}}">
                                            <textarea  class="form-control" name="reply" >{{ $feedback->reply}}</textarea>
                                            @if($errors->has('reply'))
                                                <div class="error">{{ $errors->first('reply') }}</div>
                                            @endif
                                        </div>
                                                                                
                                    </div>
                            
                                    <div class="form-group row">
                                        <div class="col-sm-3 col-sm-offset-2">
                                            <button class="btn btn-primary btn-md" type="submit">Reply</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                </div>
            </div> --}}
        @endif
    </div>
</div>
@endsection