routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/////////////// Admin Routes ////////////////
Route::name('admin.')->namespace('Auth')->middleware('guest:admin')->group(function()
{
    Route::get('/', function() {
        return redirect(route('admin.login'));
    }); 

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('login.submit');

});

Route::name('admin.')->middleware(['auth:admin'])
->group(function() {

    Route::post('logout', 'Auth\LoginController@logout')->name('logout');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/newsletter', 'HomeController@newsletter')->name('newsletter');
    Route::post('/newsletter/store', 'HomeController@newsletterstore')->name('newsletter.store');

    Route::group(['prefix' => 'setting'], function() {

        Route::get('/', 'SettingController@index')->name('setting');
        Route::post('/appname', 'SettingController@updateappname')->name('setting.appname');
        Route::post('/logo', 'SettingController@updatelogo')->name('setting.logo');
        Route::post('/copyright', 'SettingController@updatecopyright')->name('setting.copyright');
        Route::post('/email', 'SettingController@updateadminemail')->name('setting.email');
        Route::post('/password', 'SettingController@updateadminpassword')->name('setting.password');

        Route::post('/app_address', 'SettingController@updatecompanyaddress')->name('setting.app_address');
        Route::post('/app_email', 'SettingController@updatecompanyemail')->name('setting.app_email');
        Route::post('/app_mobile', 'SettingController@updatecompanymobile')->name('setting.app_mobile');
   
    });

    Route::resource('socials', SocialController::class);
    Route::resource('products', ProductController::class);
    Route::resource('procategory', ProductCategoryController::class);
    Route::resource('services', ServiceController::class);
    
    Route::get('/product/image/{id}', 'ProductController@produtimagedelete')->name('product.image.delete');
    Route::post('/products/status/{id}', 'ProductController@updatestatus')->name('product.status');
    Route::post('/services/status/{id}', 'ServiceController@updatestatus')->name('services.status');

    Route::get('/feedback', 'FeedBackController@index')->name('feedback.index');
    Route::delete('/feedback/delete/{id}', 'FeedBackController@destroy')->name('feedback.delete');
    Route::get('/feedback/{id}/show', 'FeedBackController@feedbackshow')->name('feedback.show');
    Route::post('/feedback/reply', 'FeedBackController@feedbackreply')->name('feedback.reply');


    Route::get('/content', 'ContentController@index')->name('content.index');
    Route::get('/content/{id}', 'ContentController@edit')->name('content.edit');
    Route::put('/content/{id}', 'ContentController@update')->name('content.update');
    Route::get('/content/image/{id}', 'ContentController@deleteImage')->name('content.image.delete');
    Route::get('/content/video/{id}', 'ContentController@deletevideo')->name('content.video.delete');


    Route::group(['prefix' => 'web-user'], function() {

        Route::get('/', 'WebUserController@index')->name('webuser.index');
        Route::get('/get', 'WebUserController@get')->name('webuser.get');

        Route::get('/add', 'WebUserController@addUser')->name('webuser.add');
        Route::post('/store', 'WebUserController@storeUser')->name('webuser.store');
        Route::get('/edit/{id?}', 'WebUserController@editUser')->name('webuser.edit');
        Route::get('/show/{id?}', 'WebUserController@showUser')->name('webuser.show');
        Route::post('/update', 'WebUserController@updateUser')->name('webuser.update');
        Route::get('/delete/{id?}', 'WebUserController@userdelete')->name('webuser.delete');

        Route::post('/bulk-action', 'WebUserController@bulkAction')->name('webuser.bulkAction');
        Route::post('export-excel', 'WebUserController@excel_export')->name('webuser.export.excel');
        Route::post('/status/{id}', 'WebUserController@updatestatus')->name('webuser.status');
    });

});

routes/web.php
<?php

use App\Mail\TestMail;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/fcm/{message}/{token}', function ($message, $token)
// {
//    dd(fcm($token,'user', 'Play Pause Continue', $message, []));
// });

Route::get('/welcome', function () {
    return view('welcome');
}); 
Route::get('/', [App\Http\Controllers\IndexController::class, 'index'])->name('/');
// Route::get('/', [App\Http\Controllers\IndexController::class, 'index'])->name('index');
Route::get('/contact-us', [App\Http\Controllers\IndexController::class, 'contactUs'])->name('contactus');
Route::get('/career', [App\Http\Controllers\IndexController::class, 'career'])->name('career');
Route::get('/about-us', [App\Http\Controllers\IndexController::class, 'aboutUs'])->name('aboutus');
Route::get('/privacy-policy', [App\Http\Controllers\IndexController::class, 'privacypolicy'])->name('privacypolicy');
Route::get('/term-condition', [App\Http\Controllers\IndexController::class, 'termcondition'])->name('termcondition');
Route::get('/services', [App\Http\Controllers\IndexController::class, 'services'])->name('services');
Route::get('/services/{id}', [App\Http\Controllers\IndexController::class, 'serviceById'])->name('service_by_id');
Route::get('/who-we-are', [App\Http\Controllers\IndexController::class, 'who_we_are'])->name('who_we_are');
Route::get('/our-values', [App\Http\Controllers\IndexController::class, 'our_values'])->name('our_values');
Route::get('/our-history', [App\Http\Controllers\IndexController::class, 'our_history'])->name('our_history');
Route::get('/board-of-director', [App\Http\Controllers\IndexController::class, 'board_of_director'])->name('board_of_director');
Route::get('/management-team', [App\Http\Controllers\IndexController::class, 'management_team'])->name('management_team');
Route::get('/products', [App\Http\Controllers\IndexController::class, 'products'])->name('products');
Route::get('/products/{cat_id}', [App\Http\Controllers\IndexController::class, 'productByCategory'])->name('product_by_id');
Route::get('/products/detail/{product_id}', [App\Http\Controllers\IndexController::class, 'productDetail'])->name('productDetail');

Auth::routes();

Route::post('/feedback/store', [App\Http\Controllers\IndexController::class, 'feedback'])->name('feedback.store');
Route::post('/newsletter/store', [App\Http\Controllers\IndexController::class, 'newsletter'])->name('newsletter.store');
Route::post('/validatemobile', [App\Http\Controllers\IndexController::class, 'validatemobile'])->name('validatemobile');
Route::post('/validateemail', [App\Http\Controllers\IndexController::class, 'validateemail'])->name('validateemail');
Route::post('/validateuser', [App\Http\Controllers\IndexController::class, 'validateuser'])->name('validateuser');
Route::post('/sendotptomobile', [App\Http\Controllers\IndexController::class, 'sendotptomobile'])->name('sendotptomobile');

Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/mobile', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.mobile');

Route::post('/verifyotp', [App\Http\Controllers\IndexController::class, 'verifyotp'])->name('verifyotp');
Route::get('/resend-otp/{mobile}', [App\Http\Controllers\IndexController::class, 'resendotp'])->name('resendotp');

Route::middleware(['auth:customer'])->group(function()
{
    Route::get('/test', [App\Http\Controllers\IndexController::class, 'test']);
    Route::get('/home', [App\Http\Controllers\IndexController::class, 'index'])->name('home');
    Route::post('/save-token', [App\Http\Controllers\IndexController::class, 'saveToken'])->name('save-token');


    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
   
});

resources/views/admin/home.blade.php
@extends('admin.layouts.admin')

@section('content')
    <style>
            .full-featured-box a {
            display: block;
            }
            .icon-box img {
                    display: block;
                    padding: 40px 0px;
                    width: 130px;
                    height: 130px;
                    margin: 0 auto;
        }
            .icon-box button.mybtn {
                width: 100%;
                border: none;
                color: #000;
                padding: 12px 5px;
                border-radius: 0px 0px 5px 5px;
                cursor: pointer;
            }
                button.mybtn.red {
                    background: #ffaeb9;
                }
                .feature-box {
            background: #fff;
            border-radius: 5px;
                }
                button.mybtn.gold {
                background: #dec465;
            }
            button.mybtn.orange {
                background: #edaf4b;
            }
            button.mybtn.blue {
            background: #869be7;
        }
        .full-featured-box {
            margin-bottom: 30px;
        }
        button.mybtn.pink {
            background: #fbaef9;
        }
        button.mybtn.task {
            background: #65ded8;
        }
        button.mybtn.Community {
            background: #ffd9ad;
        }
        button.mybtn.Feedback {
            background: #b9ffb9;
        }
        button.mybtn.Content {
            background: #dcb6ff;
        }
        button.mybtn.Newsletter {
            background: #feffae;
        }
        button.mybtn.Social {
            background: #72ffff;
        }
        button.mybtn.Settings {
            background: #deff8e;
        }

    </style>

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Dashboard</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.home') }}">Home</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Dashboard</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">
    
        </div>
    </div>

    
    <div class="wrapper wrapper-content animated fadeInRight">
        

        

        <div class="row">


            <div class="col-lg-4">
                <div class="full-featured-box">
                    <a href="{{ route('admin.feedback.index') }}">
                        <div class="feature-box">
                            <div class="icon-box">
                                <img src="{{asset('images/p-feedback.svg')}}">
                                <button type="button" class="mybtn Feedback">Manage Contact us</button>
                            </div>
                        </div>
                    </a> 
                </div>
            </div>

            

            <div class="col-lg-4">
                <div class="full-featured-box">
                    <a href="{{ route('admin.newsletter') }}">
                        <div class="feature-box">
                            <div class="icon-box">
                                <img src="{{asset('images/p-newsletter.svg')}}">
                                <button type="button" class="mybtn Newsletter">Manage Newsletter</button>
                            </div>
                        </div>
                    </a> 
                </div>
            </div>
            <div class="col-lg-4">
                <div class="full-featured-box">
                    <a href="{{ route('admin.socials.index') }}">
                        <div class="feature-box">
                            <div class="icon-box">
                                <img src="{{asset('images/p-social.svg')}}">
                                <button type="button" class="mybtn Social">Manage Social</button>
                            </div>
                        </div>
                    </a> 
                </div>
            </div>

            <div class="col-lg-4">
                <div class="full-featured-box">
                    <a href="{{ route('admin.setting') }}">
                        <div class="feature-box">
                            <div class="icon-box">
                                <img src="{{asset('images/p-setting.svg')}}">
                                <button type="button" class="mybtn Settings">Manage Settings</button>
                            </div>
                        </div>
                    </a> 
                </div>
            </div>



        </div>
             
       
                
    </div>
    
@endsection