routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/////////////// Admin Routes ////////////////
Route::name('admin.')->namespace('Auth')->middleware('guest:admin')->group(function()
{
    Route::get('/', function() {
        return redirect(route('admin.login'));
    }); 

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('login.submit');

});

Route::name('admin.')->middleware(['auth:admin'])
->group(function() {

    Route::post('logout', 'Auth\LoginController@logout')->name('logout');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/newsletter', 'HomeController@newsletter')->name('newsletter');
    Route::post('/newsletter/store', 'HomeController@newsletterstore')->name('newsletter.store');

    Route::group(['prefix' => 'setting'], function() {

        Route::get('/', 'SettingController@index')->name('setting');
        Route::post('/appname', 'SettingController@updateappname')->name('setting.appname');
        Route::post('/logo', 'SettingController@updatelogo')->name('setting.logo');
        Route::post('/copyright', 'SettingController@updatecopyright')->name('setting.copyright');
        Route::post('/email', 'SettingController@updateadminemail')->name('setting.email');
        Route::post('/password', 'SettingController@updateadminpassword')->name('setting.password');

        Route::post('/app_address', 'SettingController@updatecompanyaddress')->name('setting.app_address');
        Route::post('/app_email', 'SettingController@updatecompanyemail')->name('setting.app_email');
        Route::post('/app_mobile', 'SettingController@updatecompanymobile')->name('setting.app_mobile');
   
    });

    Route::resource('socials', SocialController::class);
    Route::resource('products', ProductController::class);
    Route::resource('procategory', ProductCategoryController::class);
    Route::resource('services', ServiceController::class);
    
    Route::get('/product/image/{id}', 'ProductController@produtimagedelete')->name('product.image.delete');
    Route::post('/products/status/{id}', 'ProductController@updatestatus')->name('product.status');
    Route::post('/services/status/{id}', 'ServiceController@updatestatus')->name('services.status');

    Route::get('/feedback', 'FeedBackController@index')->name('feedback.index');
    Route::delete('/feedback/delete/{id}', 'FeedBackController@destroy')->name('feedback.delete');
    Route::get('/feedback/{id}/show', 'FeedBackController@feedbackshow')->name('feedback.show');
    Route::post('/feedback/reply', 'FeedBackController@feedbackreply')->name('feedback.reply');


    Route::get('/content', 'ContentController@index')->name('content.index');
    Route::get('/content/{id}', 'ContentController@edit')->name('content.edit');
    Route::put('/content/{id}', 'ContentController@update')->name('content.update');
    Route::get('/content/image/{id}', 'ContentController@deleteImage')->name('content.image.delete');
    Route::get('/content/video/{id}', 'ContentController@deletevideo')->name('content.video.delete');


    Route::group(['prefix' => 'web-user'], function() {

        Route::get('/', 'WebUserController@index')->name('webuser.index');
        Route::get('/get', 'WebUserController@get')->name('webuser.get');

        Route::get('/add', 'WebUserController@addUser')->name('webuser.add');
        Route::post('/store', 'WebUserController@storeUser')->name('webuser.store');
        Route::get('/edit/{id?}', 'WebUserController@editUser')->name('webuser.edit');
        Route::get('/show/{id?}', 'WebUserController@showUser')->name('webuser.show');
        Route::post('/update', 'WebUserController@updateUser')->name('webuser.update');
        Route::get('/delete/{id?}', 'WebUserController@userdelete')->name('webuser.delete');

        Route::post('/bulk-action', 'WebUserController@bulkAction')->name('webuser.bulkAction');
        Route::post('export-excel', 'WebUserController@excel_export')->name('webuser.export.excel');
        Route::post('/status/{id}', 'WebUserController@updatestatus')->name('webuser.status');
    });

});

routes/web.php
<?php

use App\Mail\TestMail;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/fcm/{message}/{token}', function ($message, $token)
// {
//    dd(fcm($token,'user', 'Play Pause Continue', $message, []));
// });

Route::get('/welcome', function () {
    return view('welcome');
}); 
Route::get('/', [App\Http\Controllers\IndexController::class, 'index'])->name('/');
// Route::get('/', [App\Http\Controllers\IndexController::class, 'index'])->name('index');
Route::get('/contact-us', [App\Http\Controllers\IndexController::class, 'contactUs'])->name('contactus');
Route::get('/career', [App\Http\Controllers\IndexController::class, 'career'])->name('career');
Route::get('/about-us', [App\Http\Controllers\IndexController::class, 'aboutUs'])->name('aboutus');
Route::get('/privacy-policy', [App\Http\Controllers\IndexController::class, 'privacypolicy'])->name('privacypolicy');
Route::get('/term-condition', [App\Http\Controllers\IndexController::class, 'termcondition'])->name('termcondition');
Route::get('/services', [App\Http\Controllers\IndexController::class, 'services'])->name('services');
Route::get('/services/{id}', [App\Http\Controllers\IndexController::class, 'serviceById'])->name('service_by_id');
Route::get('/who-we-are', [App\Http\Controllers\IndexController::class, 'who_we_are'])->name('who_we_are');
Route::get('/our-values', [App\Http\Controllers\IndexController::class, 'our_values'])->name('our_values');
Route::get('/our-history', [App\Http\Controllers\IndexController::class, 'our_history'])->name('our_history');
Route::get('/board-of-director', [App\Http\Controllers\IndexController::class, 'board_of_director'])->name('board_of_director');
Route::get('/management-team', [App\Http\Controllers\IndexController::class, 'management_team'])->name('management_team');
Route::get('/products', [App\Http\Controllers\IndexController::class, 'products'])->name('products');
Route::get('/products/{cat_id}', [App\Http\Controllers\IndexController::class, 'productByCategory'])->name('product_by_id');
Route::get('/products/detail/{product_id}', [App\Http\Controllers\IndexController::class, 'productDetail'])->name('productDetail');

Auth::routes();

Route::post('/feedback/store', [App\Http\Controllers\IndexController::class, 'feedback'])->name('feedback.store');
Route::post('/newsletter/store', [App\Http\Controllers\IndexController::class, 'newsletter'])->name('newsletter.store');
Route::post('/validatemobile', [App\Http\Controllers\IndexController::class, 'validatemobile'])->name('validatemobile');
Route::post('/validateemail', [App\Http\Controllers\IndexController::class, 'validateemail'])->name('validateemail');
Route::post('/validateuser', [App\Http\Controllers\IndexController::class, 'validateuser'])->name('validateuser');
Route::post('/sendotptomobile', [App\Http\Controllers\IndexController::class, 'sendotptomobile'])->name('sendotptomobile');

Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/mobile', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.mobile');

Route::post('/verifyotp', [App\Http\Controllers\IndexController::class, 'verifyotp'])->name('verifyotp');
Route::get('/resend-otp/{mobile}', [App\Http\Controllers\IndexController::class, 'resendotp'])->name('resendotp');

Route::middleware(['auth:customer'])->group(function()
{
    Route::get('/test', [App\Http\Controllers\IndexController::class, 'test']);
    Route::get('/home', [App\Http\Controllers\IndexController::class, 'index'])->name('home');
    Route::post('/save-token', [App\Http\Controllers\IndexController::class, 'saveToken'])->name('save-token');


    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
   
});

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Product;
use Illuminate\Http\Request;
use App\Models\ProductCategory;
use App\Http\Controllers\Controller;
use App\Models\ProductImages;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['products']=Product::orderBy('id','desc')->get();
        return view('admin.products.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['productscategory']=ProductCategory::get();
        return view('admin.products.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator=Validator::make($request->all(),[
            'category_id'    => 'required|not_in:0',
            'product_code'   => 'required|unique:products,product_code',
            'product_name'   => 'required',
            'image'          => 'required',
            // 'product_image'  => 'required|array',
            'product_price'  => 'required',
            'product_description'  => 'required',
        ]);
        if($validator->fails())
        {
           
            return redirect()->back()->withErrors($validator->errors())->withInput();
        }  
        $addproduct = new Product();
        $addproduct->category_id  = $request->category_id;
        $addproduct->product_code  = $request->product_code;
        $addproduct->product_name  = $request->product_name;
        $addproduct->product_price  = $request->product_price;
        $addproduct->product_description  = $request->product_description;
        $backupLoc='public/product/';
        if(!is_dir($backupLoc)) 
        {
            Storage::makeDirectory($backupLoc, 0755, true, true);
        }

        if($request->has('image')) 
        {
            $file = $request->file('image');
            $image = time().'_'.$file->getClientOriginalName();
            $upload_success1 = $request->file('image')->storeAs('public/product',$image); 
            $addproduct->thumbnail_image =  $image; 
            
        }
        $addproduct->save();

   
        // if(count($request->product_image)>0) 
        // {
        //     if( $request->has('product_image')) 
        //     {
        //         if(count($request->product_image)>0)
        //         {
        //             foreach($request->product_image as $file)
        //             {
        //                 $image = time().'_'.$file->getClientOriginalName();
        //                 $upload_success1 = $file->storeAs('public/product',$image);
        //                 $productimages = new ProductImages(); 
        //                 $productimages->product_id = $addproduct->id;
        //                 $productimages->product_image = $image;
        //                 $productimages->save();
        //             }
        //         }
        //     }
        // }
      
        return redirect()->route('admin.products.index')->with('success','Product Added!');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['productscategory']=ProductCategory::get();
        $data['products']=Product::where('id',$id)->first();

        // dd( $data['products']->getImages);
        return view('admin.products.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       
        $validator=Validator::make($request->all(),[
            'category_id'    => 'required|not_in:0',
            'product_code'   => "required|unique:products,product_code,".$id,
            'product_name'   => 'required',
            'product_price'  => 'required',
            'product_description'  => 'required',
        ]);
        if($validator->fails())
        {
            return redirect()->back()->withErrors($validator->errors())->withInput();
        }  
         
        $addproduct = Product::where('id',$id)->first();
        $addproduct->category_id  = $request->category_id;
        $addproduct->product_code  = $request->product_code;
        $addproduct->product_name  = $request->product_name;
        $addproduct->product_price  = $request->product_price;
        $addproduct->product_description  = $request->product_description;
        $backupLoc='public/product/';
        if(!is_dir($backupLoc)) 
        {
            Storage::makeDirectory($backupLoc, 0755, true, true);
        }
  
        if($request->has('image')) 
        {          
            if( $addproduct->thumbnail_image != null)
            { 
                $filePath1 = storage_path('app/public/product/'.$addproduct->thumbnail_image);
                if(is_file($filePath1))
                {
                    unlink($filePath1);
                } 
            } 

            $file = $request->file('image');
            $image = time().'_'.$file->getClientOriginalName();
            $upload_success1 = $request->file('image')->storeAs('public/product',$image); 
            $addproduct->thumbnail_image =  $image; 
            
        }
        $addproduct->save();
        // if($request->has('product_image')) 
        // {
        //     if(count($request->product_image)>0)
        //     {
        //         foreach($request->product_image as $file)
        //         {
        //             $image = time().'_'.$file->getClientOriginalName();
        //             $upload_success1 = $file->storeAs('public/product',$image);
        //             $productimages = new ProductImages(); 
        //             $productimages->product_id = $addproduct->id;
        //             $productimages->product_image = $image;
        //             $productimages->save();
        //         }
        //     }
        // }
      

        return redirect()->route('admin.products.index')->with('success','Product Updated!');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product=Product::find($id);
        if( $product->thumbnail_image != null)
        { 
            $filePath1 = storage_path('app/public/product/'.$product->thumbnail_image);
            if(is_file($filePath1))
            {
                unlink($filePath1);
            } 
        } 
        $productimage = ProductImages::where('product_id',$id)->get();
        if(count($productimage)>0)
        {
            foreach($productimage as $file)
            {
                $product_image = storage_path('app/public/product/'.$file->product_image);
                if(is_file($product_image))
                {
                    unlink($product_image);
                } 
            }
        }
        if($product->delete())
        {
            Session::flash('success','Product Deleted!');
            return response()->json(['status' => '1']);
        }
        else
        {
            Session::flash('failed','Product  Not Deleted!');
            return response()->json(['status' => '0']);
        }
    }
    public function produtimagedelete($id)
    {
        $product=ProductImages::find($id);
        if( $product->product_image != null)
        { 
            $filePath1 = storage_path('app/public/product/'.$product->product_image);
            if(is_file($filePath1))
            {
                unlink($filePath1);
            } 
        } 
        if($product->delete())
        {
            Session::flash('success','Product Image Deleted!');
            return redirect()->back();
        }
        else
        {
            Session::flash('failed','Product Image Not Deleted!');
            return redirect()->back();
        }
    }
    public function updatestatus(Request $request)
    {
        $Product = Product::find($request->id);
        $Product->status = $request->status;
        if($Product->save())
        {
            return response()->json(['status' => '1','massage'=>'Product Status Updated!']);
        }
        else
        {
            return response()->json(['status' => '0','massage'=>'Product Status Not Updated!']);
        }
    }
    
}

resources/views/admin/products/category/edit.blade.php
@extends('admin.layouts.admin')

@push('style')
    <link href="{{ asset('css/plugins/dataTables/datatables.min.css') }}" rel="stylesheet">
@endpush

@section('content')

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-9">
            <h2>Edit Category List</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.home') }}">Home</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Product</strong>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Category</strong>
                </li>
            </ol>
            
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">

        <div class="row">
            
        
            <div class="col-lg-6 col-md-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5> </h5>
                        <div class="ibox-tools">
                            <a class="btn btn-sm btn-warning text-dark" style="color:white !important;" href="{{ route('admin.procategory.index') }}">Go to Category List</a>
                        </div>
                    </div>
                        
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover dataTables-example">
                                <thead>
                                    <tr>
                                        <th>S.No.</th>
                                        <th>Category Name</th>
                                        <th>Category Code</th>
                                        <th>Action</th>     
                                    </tr>
                                </thead>
                                <tbody >
                                    @forelse ($productscategory as $item)
                                        <tr>
                                            <td>{{$loop->iteration}}</td>
                                            <td>{{$item->cat_name}} </td>
                                            <td>{{$item->cat_code}}</td>
                                            <td>
                                                <a class="btn btn-xs text-light btn-warning"  href="{{ route('admin.procategory.edit', $item->id)}}"><i class="fa fa-pencil"></i></a>            
                                            </td>
                                        </tr>
                                    @empty
                                        
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-md-12">
                <div class="ibox">
                    <div class="ibox-title">
                        <h5>Edit Product Category</h5>
                    </div>
                    <div class="ibox-content">
                        <form action="{{ route('admin.procategory.update',$singlecategory->id) }}" method="POST">
                            @csrf   
                            @method('PUT')                         
                            <div class="form-group row">
                                <div class="col-sm-2 col-sm-offset-2">
                                    <b><span>Category Name </span></b>
                                </div>
                                <div class="col-sm-7 mb-2">
                                    <input type="text" class="form-control" value="{{ $singlecategory->cat_name }}" name="cat_name" placeholder="" />
                                    @if($errors->has('cat_name'))
                                        <div class="error">{{ $errors->first('cat_name') }}</div>
                                    @endif
                                </div>

                            </div>
                            <div class="form-group row">
                                <div class="col-sm-2 col-sm-offset-2">
                                    <b><span>Category Code </span></b>
                                </div>
                                <div class="col-sm-7 mb-2">
                                    <input type="text" class="form-control" value="{{ $singlecategory->cat_code }}" name="cat_code" placeholder="" />
                                    @if($errors->has('cat_code'))
                                        <div class="error">{{ $errors->first('cat_code') }}</div>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-3 col-sm-offset-2">
                                    <button class="btn btn-dark btn-md" type="submit">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
        </div>
        </div>
    </div>

@endsection

@push('script')
    <script src="{{ asset('js/plugins/dataTables/datatables.min.js') }}"></script>
    <script src="{{ asset('js/plugins/dataTables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{asset('js/plugins/sweetalert/sweetalert.min.js')}}"></script>

    <script>
        $(document).ready(function(){
            $('.dataTables-example').dataTable( {
                "columnDefs": [{ "orderable": false, "targets": [3] }]
            });
        });
    </script>
@endpush

resources/views/admin/products/category/index.blade.php
@extends('admin.layouts.admin')

@push('style')
    <link href="{{ asset('css/plugins/dataTables/datatables.min.css') }}" rel="stylesheet">
@endpush

@section('content')

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-9">
            <h2> Category List</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.home') }}">Home</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Product</strong>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Category</strong>
                </li>
            </ol>
            
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">

        <div class="row">
            
        
            <div class="col-lg-6 col-md-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5></h5>
                        <div class="ibox-tools">
                            {{-- <a class="btn btn-sm btn-warning" style="color:black !important;" href="{{ route('admin.products.index') }}">Go to Product List</a> --}}
                        </div>
                    </div>
                        
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover dataTables-example">
                                <thead>
                                    <tr>
                                        <th>S.No.</th>
                                        <th>Category Name</th>
                                        <th>Category Code</th>
                                        <th>Action</th>     
                                    </tr>
                                </thead>
                                <tbody >
                                    @forelse ($productscategory as $item)
                                        <tr>
                                            <td>{{$loop->iteration}}</td>
                                            <td>{{$item->cat_name}} </td>
                                            <td>{{$item->cat_code}}</td>
                                            <td>
                                                <a class="btn btn-xs text-light btn-warning"  href="{{ route('admin.procategory.edit', $item->id)}}"><i class="fa fa-pencil"></i></a>            
                                                <button  class="btn btn-xs btn-dark" onclick="deletemyTopic({{$item->id}})"><i class="fa fa-trash"></i></button>
                                            </td>
                                        </tr>
                                    @empty
                                        
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-md-12">
                <div class="ibox">
                    <div class="ibox-title">
                        <h5>Add Product Category</h5>
                    </div>
                    <div class="ibox-content">
                        <form action="{{ route('admin.procategory.store') }}" method="POST">
                            @csrf                            
                            <div class="form-group row">
                                <div class="col-sm-2 col-sm-offset-2">
                                    <b><span>Category Name </span></b>
                                </div>
                                <div class="col-sm-7 mb-2">
                                    <input type="text" class="form-control" value="{{ old('cat_name') }}" name="cat_name" placeholder="" />
                                    @if($errors->has('cat_name'))
                                        <div class="error">{{ $errors->first('cat_name') }}</div>
                                    @endif
                                </div>
                            </div>
                          
                            <div class="form-group row">
                                <div class="col-sm-2 col-sm-offset-2">
                                    <b><span>Category Code </span></b>
                                </div>
                                <div class="col-sm-7 mb-2">
                                    <input type="text" class="form-control" value="{{ old('cat_code') }}" name="cat_code" placeholder="" />
                                    @if($errors->has('cat_code'))
                                        <div class="error">{{ $errors->first('cat_code') }}</div>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-3 col-sm-offset-2">
                                    <button class="btn btn-dark btn-md" type="submit">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
        </div>
        </div>
    </div>

@endsection

@push('script')
    <script src="{{ asset('js/plugins/dataTables/datatables.min.js') }}"></script>
    <script src="{{ asset('js/plugins/dataTables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{asset('js/plugins/sweetalert/sweetalert.min.js')}}"></script>

    <script>
        $(document).ready(function(){
            $('.dataTables-example').dataTable( {
                "columnDefs": [{ "orderable": false, "targets": [3] }]
            });
        });

        function deletemyTopic(id) 
        {
            var id= id;
            var url="{{ url('admin/procategory')}}"+'/'+id;
            $.ajax({
                type: 'POST',
                dataType: 'json',
                data: {
                    id: id,
                    _token: "{{ csrf_token() }}",
                    _method: 'DELETE'
                },
                url: url,
                success: function (data) {
                    if(data.status=='1')
                    {
                        location.reload();
                    }
                    if(data.status=='0')
                    {
                        location.reload();
                    }
                },
                error: (err) => {
                    console.log(err);
                    swal("Server Error!", "", "error");
                },
            });
        
        }

    </script>
@endpush