routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/////////////// Admin Routes ////////////////
Route::name('admin.')->namespace('Auth')->middleware('guest:admin')->group(function()
{
    Route::get('/', function() {
        return redirect(route('admin.login'));
    }); 

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('login.submit');

});

Route::name('admin.')->middleware(['auth:admin'])
->group(function() {

    Route::post('logout', 'Auth\LoginController@logout')->name('logout');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/newsletter', 'HomeController@newsletter')->name('newsletter');
    Route::post('/newsletter/store', 'HomeController@newsletterstore')->name('newsletter.store');

    Route::group(['prefix' => 'setting'], function() {

        Route::get('/', 'SettingController@index')->name('setting');
        Route::post('/appname', 'SettingController@updateappname')->name('setting.appname');
        Route::post('/logo', 'SettingController@updatelogo')->name('setting.logo');
        Route::post('/copyright', 'SettingController@updatecopyright')->name('setting.copyright');
        Route::post('/email', 'SettingController@updateadminemail')->name('setting.email');
        Route::post('/password', 'SettingController@updateadminpassword')->name('setting.password');

        Route::post('/app_address', 'SettingController@updatecompanyaddress')->name('setting.app_address');
        Route::post('/app_email', 'SettingController@updatecompanyemail')->name('setting.app_email');
        Route::post('/app_mobile', 'SettingController@updatecompanymobile')->name('setting.app_mobile');
   
    });

    Route::resource('socials', SocialController::class);
    Route::resource('products', ProductController::class);
    Route::resource('procategory', ProductCategoryController::class);
    Route::resource('services', ServiceController::class);
    
    Route::get('/product/image/{id}', 'ProductController@produtimagedelete')->name('product.image.delete');
    Route::post('/products/status/{id}', 'ProductController@updatestatus')->name('product.status');
    Route::post('/services/status/{id}', 'ServiceController@updatestatus')->name('services.status');

    Route::get('/feedback', 'FeedBackController@index')->name('feedback.index');
    Route::delete('/feedback/delete/{id}', 'FeedBackController@destroy')->name('feedback.delete');
    Route::get('/feedback/{id}/show', 'FeedBackController@feedbackshow')->name('feedback.show');
    Route::post('/feedback/reply', 'FeedBackController@feedbackreply')->name('feedback.reply');


    Route::get('/content', 'ContentController@index')->name('content.index');
    Route::get('/content/{id}', 'ContentController@edit')->name('content.edit');
    Route::put('/content/{id}', 'ContentController@update')->name('content.update');
    Route::get('/content/image/{id}', 'ContentController@deleteImage')->name('content.image.delete');
    Route::get('/content/video/{id}', 'ContentController@deletevideo')->name('content.video.delete');


    Route::group(['prefix' => 'web-user'], function() {

        Route::get('/', 'WebUserController@index')->name('webuser.index');
        Route::get('/get', 'WebUserController@get')->name('webuser.get');

        Route::get('/add', 'WebUserController@addUser')->name('webuser.add');
        Route::post('/store', 'WebUserController@storeUser')->name('webuser.store');
        Route::get('/edit/{id?}', 'WebUserController@editUser')->name('webuser.edit');
        Route::get('/show/{id?}', 'WebUserController@showUser')->name('webuser.show');
        Route::post('/update', 'WebUserController@updateUser')->name('webuser.update');
        Route::get('/delete/{id?}', 'WebUserController@userdelete')->name('webuser.delete');

        Route::post('/bulk-action', 'WebUserController@bulkAction')->name('webuser.bulkAction');
        Route::post('export-excel', 'WebUserController@excel_export')->name('webuser.export.excel');
        Route::post('/status/{id}', 'WebUserController@updatestatus')->name('webuser.status');
    });

});

routes/web.php
<?php

use App\Mail\TestMail;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/fcm/{message}/{token}', function ($message, $token)
// {
//    dd(fcm($token,'user', 'Play Pause Continue', $message, []));
// });

Route::get('/welcome', function () {
    return view('welcome');
}); 
Route::get('/', [App\Http\Controllers\IndexController::class, 'index'])->name('/');
// Route::get('/', [App\Http\Controllers\IndexController::class, 'index'])->name('index');
Route::get('/contact-us', [App\Http\Controllers\IndexController::class, 'contactUs'])->name('contactus');
Route::get('/career', [App\Http\Controllers\IndexController::class, 'career'])->name('career');
Route::get('/about-us', [App\Http\Controllers\IndexController::class, 'aboutUs'])->name('aboutus');
Route::get('/privacy-policy', [App\Http\Controllers\IndexController::class, 'privacypolicy'])->name('privacypolicy');
Route::get('/term-condition', [App\Http\Controllers\IndexController::class, 'termcondition'])->name('termcondition');
Route::get('/services', [App\Http\Controllers\IndexController::class, 'services'])->name('services');
Route::get('/services/{id}', [App\Http\Controllers\IndexController::class, 'serviceById'])->name('service_by_id');
Route::get('/who-we-are', [App\Http\Controllers\IndexController::class, 'who_we_are'])->name('who_we_are');
Route::get('/our-values', [App\Http\Controllers\IndexController::class, 'our_values'])->name('our_values');
Route::get('/our-history', [App\Http\Controllers\IndexController::class, 'our_history'])->name('our_history');
Route::get('/board-of-director', [App\Http\Controllers\IndexController::class, 'board_of_director'])->name('board_of_director');
Route::get('/management-team', [App\Http\Controllers\IndexController::class, 'management_team'])->name('management_team');
Route::get('/products', [App\Http\Controllers\IndexController::class, 'products'])->name('products');
Route::get('/products/{cat_id}', [App\Http\Controllers\IndexController::class, 'productByCategory'])->name('product_by_id');
Route::get('/products/detail/{product_id}', [App\Http\Controllers\IndexController::class, 'productDetail'])->name('productDetail');

Auth::routes();

Route::post('/feedback/store', [App\Http\Controllers\IndexController::class, 'feedback'])->name('feedback.store');
Route::post('/newsletter/store', [App\Http\Controllers\IndexController::class, 'newsletter'])->name('newsletter.store');
Route::post('/validatemobile', [App\Http\Controllers\IndexController::class, 'validatemobile'])->name('validatemobile');
Route::post('/validateemail', [App\Http\Controllers\IndexController::class, 'validateemail'])->name('validateemail');
Route::post('/validateuser', [App\Http\Controllers\IndexController::class, 'validateuser'])->name('validateuser');
Route::post('/sendotptomobile', [App\Http\Controllers\IndexController::class, 'sendotptomobile'])->name('sendotptomobile');

Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/mobile', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.mobile');

Route::post('/verifyotp', [App\Http\Controllers\IndexController::class, 'verifyotp'])->name('verifyotp');
Route::get('/resend-otp/{mobile}', [App\Http\Controllers\IndexController::class, 'resendotp'])->name('resendotp');

Route::middleware(['auth:customer'])->group(function()
{
    Route::get('/test', [App\Http\Controllers\IndexController::class, 'test']);
    Route::get('/home', [App\Http\Controllers\IndexController::class, 'index'])->name('home');
    Route::post('/save-token', [App\Http\Controllers\IndexController::class, 'saveToken'])->name('save-token');


    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
   
});

app/Models/User.php
<?php

namespace App\Models;

use Laravel\Passport\HasApiTokens;
use Illuminate\Support\Facades\Storage;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'my_refer_code',
        'user_type',
        'dob',
        'mobile',
        'address',
        'GST_number',
        'refferal_code',
        'send_password',
        'block',
        'latitude',
        'longitude',
        'fcm_token',
        'wallet_pin',
        'user_level',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'send_password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'user_level' => 'int',
        'block' => 'int',
    ];

    public function findForPassport($username)
    {
        return $this->where('email', $username)
        ->orWhere('mobile', $username)
        ->first();
    }

    public function getProfileImageAttribute($value)
    {
        return $value ? url(Storage::url('userprofile/'.$value)) : null;
    }

    public function getCreatedAtAttribute($value)
    {
        return $value ? \Carbon\Carbon::parse($value)->format('Y-m-d'): null;
    }

}

resources/views/admin/user/edit_web_user.blade.php
@extends('admin.layouts.admin')

@section('content')

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-9">
            <h2>Edit User</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.home') }}">Home</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Manage User</strong>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Website Edit User</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">

        <div class="row">
            <div class="col-lg-12">
                    <div class="ibox">
                        <div class="ibox-title">
                            <h5></h5>
                        </div>
                        <div class="ibox-content">
                            <form action="{{ route('admin.webuser.update') }}" method="POST">
                                @csrf

                                <div class="form-group row">
                                    <div class="col-sm-2 col-sm-offset-2">
                                        <b><span>Name </span></b>
                                    </div>
                                    <div class="col-sm-8 mb-2">
                                        <input type="hidden" class="form-control" name="id" value="{{ $user->id}}" />
                                        <input type="text" class="form-control" name="name" value="{{ $user->name}}" />
                                        @if($errors->has('name'))
                                        <div class="error">{{ $errors->first('name') }}</div>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <div class="col-sm-2 col-sm-offset-2">
                                        <b><span>Email </span></b>
                                    </div>
                                    <div class="col-sm-8 mb-2">
                                        <input type="text" class="form-control" name="email" value="{{ $user->email}}" />
                                        @if($errors->has('email'))
                                        <div class="error">{{ $errors->first('email') }}</div>
                                        @endif
                                    </div>
                                </div>
                            
                                <div class="form-group row">
                                    <div class="col-sm-2 col-sm-offset-2">
                                        <b><span>Mobile </span></b>
                                    </div>
                                    <div class="col-sm-8 mb-2">
                                        <input type="text" class="form-control" name="mobile" value="{{ $user->mobile}}" />
                                        @if($errors->has('mobile'))
                                        <div class="error">{{ $errors->first('mobile') }}</div>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <div class="col-sm-2 col-sm-offset-2">
                                        <b><span>password </span></b>
                                    </div>
                                    <div class="col-sm-8 mb-2">
                                        <div class="input-group">
                                            <span class="input-group-prepend"> 
                                                <button onclick="myFunction3('password')" type="button" class="btn btn-primary"><i id="conpass" class="fa fa-eye-slash"></i></button>
                                            </span>
                                            <input id="password" type="password" class="form-control" min="6" name="password" placeholder="Enter Password if you want to update Or Leave Blank"/>
                                            @if($errors->has('password'))
                                            <div class="error">{{ $errors->first('password') }}</div>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <div class="col-sm-2 col-sm-offset-2">
                                        <b><span>Status </span></b>
                                    </div>
                                    <div class="col-sm-8 mb-2">
                                        <input type="checkbox" name="status" class="js-switch" @if($user->block == '1') checked @endif />
                                        @if($errors->has('status'))
                                        <div class="error">{{ $errors->first('status') }}</div>
                                        @endif
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <div class="col-sm-3 col-sm-offset-2">
                                        <button class="btn btn-primary btn-md" type="submit">Update</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
            </div>
        </div>

    </div>

@endsection

@push('script')
    <script>

        var elem = document.querySelector('.js-switch');
        var switchery = new Switchery(elem, { color: '#1AB394' });

        function myFunction3(id)
        {
            let el = $('#password');

            if(el.hasClass('fa-eye-slash'))
            {
                el.removeClass('fa-eye-slash');
                el.addClass('fa-eye');
                $('#'+id).attr('type', 'text');
            }
            else
            {
                el.removeClass('fa-eye');
                el.addClass('fa-eye-slash');
                $('#'+id).attr('type', 'password');
            }
        }
    </script>
@endpush

resources/views/admin/user/show_web_user.blade.php
@extends('admin.layouts.admin')

@section('content')

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-9">
            <h2> User Detail</h2>
            
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.home') }}">Home</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Manage User</strong>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Website User Detail</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">

        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-content">
                            <div class="flot-chart">
                                <div class="flot-chart-content" id="flot-bar-chart">
                                    @if( $user->profile_image!=null)
                                        <div class="row">
                                             <div class="col-md-1 "><b> </b></div>
                                            <div class="col-md-11 text-left"><img style="height:200px;width:200px;" src="{{$user->profile_image}}"/></div>
                                        </div>  
                                    @endif
                                    <div class="row">
                                        <div class="col-md-2 "><b>Name </b></div>
                                        <div class="col-md-10 "> {{ $user->name}}</div>
                                    
                                    </div>
                                     @if( $user->email!=null)
                                    <div class="row">
                                        <div class="col-md-2"><b>Email  </b></div>
                                        <div class="col-md-10"> {{ $user->email?$user->email:'N/A'}}</div>
                                    </div>
                                     @endif
                                    @if( $user->mobile!=null)
                                    <div class="row">
                                        <div class="col-md-2"><b>Mobile  </b></div>
                                        <div class="col-md-10"> {{ $user->mobile?$user->mobile:'N/A'}}</div>
                                    </div>
                                    @endif
                                    <div class="row">
                                        <div class="col-md-2"><b>User Code </b></div>
                                        <div class="col-md-10"> {{ $user->my_refer_code}}</div>
                                    </div>  
                                    <div class="row">
                                        <div class="col-md-2"><b>User Type </b></div>
                                        <div class="col-md-10"> {{ $user->user_type}}</div>
                                    </div>
                                    @if( $user->dob!=null)
                                        <div class="row">
                                            <div class="col-md-2"><b>DOB </b></div>
                                            <div class="col-md-10"> {{ Carbon\Carbon::parse($user->dob)->format('d M Y')}}</div>
                                        </div>  
                                    @endif
                                    @if( $user->address!=null)
                                     <div class="row">
                                        <div class="col-md-2"><b>Address </b></div>
                                        <div class="col-md-10"> {{ $user->address}}</div>
                                    </div>
                                    @endif
                                    <div class="row">
                                        <div class="col-md-2"><b>Status </b></div>
                                        <div class="col-md-10"> {{ $user->block==1?'Active':'Inactive'}}</div>
                                    </div> 
                                     <div class="row">
                                        <div class="col-md-2"><b>User Level </b></div>
                                        <div class="col-md-10"> {{ $user->user_level}}</div>
                                    </div> 
                                    @if( $user->GST_number!=null)
                                        <div class="row">
                                            <div class="col-md-2"><b>GST Number </b></div>
                                            <div class="col-md-10"> {{ $user->GST_number}}</div>
                                        </div>  
                                    @endif
                                    @if( $user->latitude !=null)
                                        <div class="row">
                                            <div class="col-md-2"><b>Latitude </b></div>
                                            <div class="col-md-10"> {{ $user->latitude }}</div>
                                        </div>  
                                    @endif
                                    @if( $user->longitude!=null)
                                        <div class="row">
                                            <div class="col-md-2"><b>Longitude </b></div>
                                            <div class="col-md-10"> {{ $user->longitude}}</div>
                                        </div>  
                                    @endif
                                    <div class="row">
                                        <div class="col-md-2"><b>Date </b></div>
                                        <div class="col-md-10"> {{ Carbon\Carbon::parse($user->created_at)->format('d M Y')}}</div>
                                    </div>                              
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

@endsection

@push('script')
    <script>

        var elem = document.querySelector('.js-switch');
        var switchery = new Switchery(elem, { color: '#1AB394' });

    </script>
@endpush

resources/views/admin/user/webindex.blade.php
@extends('admin.layouts.admin')

@push('style')
    <link href="{{ asset('css/plugins/dataTables/datatables.min.css') }}" rel="stylesheet">
@endpush

@section('content')

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-9">
            <h2>Website User List</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.home') }}">Home</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Manage User</strong>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Website User List</strong>
                </li>
            </ol>

        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5>
                            </h5>
                        {{-- <div class="ibox-tools">
                            <a class="btn btn-sm btn-dark" href="{{ route('admin.survey.create') }}"><i
                                    class="fa fa-plus text-light"></i></a>
                        </div> --}}
                    </div>

                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover dataTables-example">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>S.No.</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Mobile</th>
                                        <th>Registered Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($user as $item)
                                        <tr>
                                            <td></td>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $item->name }}</td>
                                            <td>{{ $item->email }}</td>
                                            <td>{{ $item->mobile }}</td>
                                            <td>{{ Carbon\Carbon::parse($item->created_at)->format('d M Y') }}</td>
                                        </tr>
                                    @empty

                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@push('script')
    <script src="{{ asset('js/plugins/dataTables/datatables.min.js') }}"></script>
    <script src="{{ asset('js/plugins/dataTables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('js/plugins/sweetalert/sweetalert.min.js') }}"></script>

    <script>
        $(document).ready(function() {
            $('.dataTables-example').DataTable({
                dom: "<'row'<'col-sm-4'l><'col-sm-4 text-center'B><'col-sm-4'f>>" +
                "<'row'<'col-sm-12'tr>>" +
                "<'row'<'col-sm-7'p>>",
                buttons:[
                        {
                                extend: 'excel',
                                footer: false,
                                className: 'btn btn-dark',
                                init: function(api, node, config) {
                                $(node).removeClass('btn-default')
                                }
                        }       
                    ]
            });
            $('.buttons-excel').html('Export Excel');
        });
    </script>
@endpush